--- 
clone: 
  depth: 1
kind: pipeline
name : Lain erofs
version: Lain-erofs
steps:
 - name: Lain
   image: fadlyas/kernel_dockerfile
   environment:
     token:
       from_secret: token
   commands:
     - bash kernel.sh

---
clone:
  depth: 1
kind: pipeline
name : Lain non-erofs
version: Lain-nonerofs
steps:
 - name: Lain-nonerofs
   image: fadlyas/kernel_dockerfile
   environment:
     token:
       from_secret: token
   commands:
     - git apply nonerofs.patch
     - bash kernel1.sh
